/*
 * Generated by @gcoredev/FastEdge-sdk-js fastedge-init
 */

import { getStaticServer, createStaticAssetsCache } from "@gcoredev/fastedge-sdk-js";
import { staticAssetManifest } from "./build/static-server-manifest.js";
import { serverConfig } from "./build-config.js";

const staticAssets = createStaticAssetsCache(staticAssetManifest);

const staticServer = getStaticServer(serverConfig, staticAssets);

async function handleRequest(event) {
  const response = await staticServer.serveRequest(event.request);
  if (response != null) {
    return response;
  }

  return new Response("Not found", { status: 404 });
}

addEventListener("fetch", (event) => event.respondWith(handleRequest(event)));
